version: '2'

services:
  ixa-pipe-tok:
    build: ./ixa-pipes/ixa-pipe-tok
    command: "/usr/local/bin/run-ixa-tok.sh"
    networks:
      - web-tier
    volumes:
      - ./ixa-pipes/data:/data
    ports:
      - "2030:2030"
  ixa-pipe-pos:
    build: ./ixa-pipes/ixa-pipe-pos
    command: "/usr/local/bin/run-ixa-pos.sh"
    networks:
      - web-tier
    volumes:
      - ./ixa-pipes/data:/data
    ports:
      - "2040:2040"
  ixa-pipe-tok:
    build: ./ixa-pipes/ixa-pipe-nerc
    command: "/usr/local/bin/run-ixa-nerc.sh"
    networks:
      - web-tier
    volumes:
      - ./ixa-pipes/data:/data
    ports:
      - "2060:2060"
  corenlp:
    image: oaraque/corenlpserver
    ports:
      - "9000:9000"
    networks:
      - web-tier

networks:
  web-tier:
    driver: bridge
